---
- hosts: iosv1
  gather_facts: no
  connection: local

  vars: 
    dhcpserver:
       host: "{{ inventory_hostname }}"
       username: cisco
       password: cisco
       transport: cli


  tasks: 
    - name: configuring Interface GigabitEthernet 0/1
      ios_config: 
        lines: 
          - ip address 1.1.1.1 255.0.0.0
          - no shutdown
        parents: interface GigabitEthernet 0/1
        match: exact 
        provider: "{{ dhcpserver }}"

    - name: Create a DHCP IP address pool for the IP addresses we wanted
      ios_config:
        lines:
          - network 1.1.1.0 /8
          - domain-name devopsansible.com
          - dns-server 1.1.1.10 1.1.1.11
          - default-router 1.1.1.1
          - lease 7
          - exit
        parents: ip dhcp pool mypool
        match: exact
        provider: "{{ dhcpserver }}"
    - name: verify DHCP configurations
      ios_command:
        provider: "{{ dhcpserver }}"
        commands:
          - sh run
      register: result1
    - debug: var=result1.stdout_lines

