---
- name: Execute Show ARP and display output
  hosts: ios
  gather_facts: no
  tasks:
  - raw: "show arp vrf Mgmt-intf"
    register: result
    changed_when: False
  - debug: var=result.stdout_lines

