# roles/webserver/tasks/main.yml
---
- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install PHP module for Apache
  apt: name=libapache2-mod-php5 state=present

- name: 3. start Apache
  service: name=apache2 state=running enabled=yes

- name: 4. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- name: 4. install Hello World PHP script for database verification
  copy: src=db.php dest=/var/www/html/db.php mode=0664

- name: 6. install MySQL extension for PHP
  apt: name=php5-mysql state=present

- name: 7. restart apache service reflect Mysql extenction
  service: name=apache2 state=restarted
