---
- hosts: nxos
  name:  configure interfaces
  tags:  interface
  tasks:
  - nxos_interface:
      provider: "{{cli}}"
      interface: "{{item.interface}}"
      admin_state: up
    with_items: "{{interfaces}}"
    when: "{{ item.interface is defined }}"
